### ISSUE TITLE
Suggestion: Add save configuration file and load configuration file

### ISSUE THREAD

**Issue by monkeycc** [farzadshayanfar/nodiumpy#1]
1. Load the JSON configuration file

2. Save the JSON configuration file

**Comment by farzadshayanfar** [comment]
Since at the moment we don't have a settings dialog, saving and loading does not serve any purpose. I was thinking of exposing params such as some theme settings, DPG refresh rate, and node tree update rate in a settings dialog, then saving and loading the config file will make sense. At the moment the values there are just treated as constants.
